# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES +=
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lraylib
LDDEPS +=
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/magicex
OBJDIR = obj/Debug
DEFINES +=
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -g3 -O0 -fno-omit-frame-pointer -fsanitize=address -fsanitize=leak
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -g3 -O0 -fno-omit-frame-pointer -fsanitize=address -fsanitize=leak
ALL_LDFLAGS += $(LDFLAGS) -fsanitize=address -fsanitize=leak
define POSTBUILDCMDS
	@echo Running postbuild commands
	cp -r assets "bin/Debug/assets"
endef

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/magicex
OBJDIR = obj/Release
DEFINES += -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s
define POSTBUILDCMDS
	@echo Running postbuild commands
	cp -r assets "bin/Release/assets"
endef

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/aoespell.o
GENERATED += $(OBJDIR)/areas.o
GENERATED += $(OBJDIR)/boltspell.o
GENERATED += $(OBJDIR)/charactereffectentity.o
GENERATED += $(OBJDIR)/charactermenu.o
GENERATED += $(OBJDIR)/containerentity.o
GENERATED += $(OBJDIR)/creatureentity.o
GENERATED += $(OBJDIR)/data.o
GENERATED += $(OBJDIR)/detailspanel.o
GENERATED += $(OBJDIR)/dialguemenu.o
GENERATED += $(OBJDIR)/dialogue.o
GENERATED += $(OBJDIR)/doorentity.o
GENERATED += $(OBJDIR)/endscene.o
GENERATED += $(OBJDIR)/enduilayer.o
GENERATED += $(OBJDIR)/entityspawner.o
GENERATED += $(OBJDIR)/environmentalentity.o
GENERATED += $(OBJDIR)/events.o
GENERATED += $(OBJDIR)/game.o
GENERATED += $(OBJDIR)/gamescene.o
GENERATED += $(OBJDIR)/gameuilayer.o
GENERATED += $(OBJDIR)/input.o
GENERATED += $(OBJDIR)/instantspell.o
GENERATED += $(OBJDIR)/itemgenerator.o
GENERATED += $(OBJDIR)/itemgrid.o
GENERATED += $(OBJDIR)/label.o
GENERATED += $(OBJDIR)/layergen.o
GENERATED += $(OBJDIR)/ldtk.o
GENERATED += $(OBJDIR)/loottables.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/mapgen.o
GENERATED += $(OBJDIR)/mapmenu.o
GENERATED += $(OBJDIR)/modulemenu.o
GENERATED += $(OBJDIR)/modules.o
GENERATED += $(OBJDIR)/mushroomentity.o
GENERATED += $(OBJDIR)/npcentity.o
GENERATED += $(OBJDIR)/pathgen.o
GENERATED += $(OBJDIR)/pausemenu.o
GENERATED += $(OBJDIR)/playercharacter.o
GENERATED += $(OBJDIR)/resources.o
GENERATED += $(OBJDIR)/scenemanager.o
GENERATED += $(OBJDIR)/scenerygen.o
GENERATED += $(OBJDIR)/shelterscene.o
GENERATED += $(OBJDIR)/shelteruilayer.o
GENERATED += $(OBJDIR)/spelldata.o
GENERATED += $(OBJDIR)/spelldetailspanel.o
GENERATED += $(OBJDIR)/spellgenmenu.o
GENERATED += $(OBJDIR)/spellpreview.o
GENERATED += $(OBJDIR)/spellstatinterface.o
GENERATED += $(OBJDIR)/splashscene.o
GENERATED += $(OBJDIR)/stagingscene.o
GENERATED += $(OBJDIR)/staginguilayer.o
GENERATED += $(OBJDIR)/statusbar.o
GENERATED += $(OBJDIR)/subscene.o
GENERATED += $(OBJDIR)/testdummy.o
GENERATED += $(OBJDIR)/tilelayer.o
GENERATED += $(OBJDIR)/titlescene.o
GENERATED += $(OBJDIR)/titleuilayer.o
GENERATED += $(OBJDIR)/tradegrid.o
GENERATED += $(OBJDIR)/transitions.o
GENERATED += $(OBJDIR)/utils.o
GENERATED += $(OBJDIR)/viewport.o
OBJECTS += $(OBJDIR)/aoespell.o
OBJECTS += $(OBJDIR)/areas.o
OBJECTS += $(OBJDIR)/boltspell.o
OBJECTS += $(OBJDIR)/charactereffectentity.o
OBJECTS += $(OBJDIR)/charactermenu.o
OBJECTS += $(OBJDIR)/containerentity.o
OBJECTS += $(OBJDIR)/creatureentity.o
OBJECTS += $(OBJDIR)/data.o
OBJECTS += $(OBJDIR)/detailspanel.o
OBJECTS += $(OBJDIR)/dialguemenu.o
OBJECTS += $(OBJDIR)/dialogue.o
OBJECTS += $(OBJDIR)/doorentity.o
OBJECTS += $(OBJDIR)/endscene.o
OBJECTS += $(OBJDIR)/enduilayer.o
OBJECTS += $(OBJDIR)/entityspawner.o
OBJECTS += $(OBJDIR)/environmentalentity.o
OBJECTS += $(OBJDIR)/events.o
OBJECTS += $(OBJDIR)/game.o
OBJECTS += $(OBJDIR)/gamescene.o
OBJECTS += $(OBJDIR)/gameuilayer.o
OBJECTS += $(OBJDIR)/input.o
OBJECTS += $(OBJDIR)/instantspell.o
OBJECTS += $(OBJDIR)/itemgenerator.o
OBJECTS += $(OBJDIR)/itemgrid.o
OBJECTS += $(OBJDIR)/label.o
OBJECTS += $(OBJDIR)/layergen.o
OBJECTS += $(OBJDIR)/ldtk.o
OBJECTS += $(OBJDIR)/loottables.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/mapgen.o
OBJECTS += $(OBJDIR)/mapmenu.o
OBJECTS += $(OBJDIR)/modulemenu.o
OBJECTS += $(OBJDIR)/modules.o
OBJECTS += $(OBJDIR)/mushroomentity.o
OBJECTS += $(OBJDIR)/npcentity.o
OBJECTS += $(OBJDIR)/pathgen.o
OBJECTS += $(OBJDIR)/pausemenu.o
OBJECTS += $(OBJDIR)/playercharacter.o
OBJECTS += $(OBJDIR)/resources.o
OBJECTS += $(OBJDIR)/scenemanager.o
OBJECTS += $(OBJDIR)/scenerygen.o
OBJECTS += $(OBJDIR)/shelterscene.o
OBJECTS += $(OBJDIR)/shelteruilayer.o
OBJECTS += $(OBJDIR)/spelldata.o
OBJECTS += $(OBJDIR)/spelldetailspanel.o
OBJECTS += $(OBJDIR)/spellgenmenu.o
OBJECTS += $(OBJDIR)/spellpreview.o
OBJECTS += $(OBJDIR)/spellstatinterface.o
OBJECTS += $(OBJDIR)/splashscene.o
OBJECTS += $(OBJDIR)/stagingscene.o
OBJECTS += $(OBJDIR)/staginguilayer.o
OBJECTS += $(OBJDIR)/statusbar.o
OBJECTS += $(OBJDIR)/subscene.o
OBJECTS += $(OBJDIR)/testdummy.o
OBJECTS += $(OBJDIR)/tilelayer.o
OBJECTS += $(OBJDIR)/titlescene.o
OBJECTS += $(OBJDIR)/titleuilayer.o
OBJECTS += $(OBJDIR)/tradegrid.o
OBJECTS += $(OBJDIR)/transitions.o
OBJECTS += $(OBJDIR)/utils.o
OBJECTS += $(OBJDIR)/viewport.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking magicex
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning magicex
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/utils.o: src/core/utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/game.o: src/game.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/areas.o: src/game/areas.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/data.o: src/game/data.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dialogue.o: src/game/dialogue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/charactereffectentity.o: src/game/entities/charactereffectentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/containerentity.o: src/game/entities/containerentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/creatureentity.o: src/game/entities/creatureentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/doorentity.o: src/game/entities/doorentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/entityspawner.o: src/game/entities/entityspawner.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/environmentalentity.o: src/game/entities/environmentalentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mushroomentity.o: src/game/entities/mushroomentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/npcentity.o: src/game/entities/npcentity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/playercharacter.o: src/game/entities/playercharacter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/testdummy.o: src/game/entities/testdummy.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/events.o: src/game/events.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/input.o: src/game/input.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/itemgenerator.o: src/game/itemgenerator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/itemgrid.o: src/game/itemgrid.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/label.o: src/game/label.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ldtk.o: src/game/ldtk.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/loottables.o: src/game/loottables.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mapgen.o: src/game/mapgen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layergen.o: src/game/mapgen/layergen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pathgen.o: src/game/mapgen/pathgen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scenerygen.o: src/game/mapgen/scenerygen.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/modules.o: src/game/modules.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/resources.o: src/game/resources.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scenemanager.o: src/game/scenemanager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/charactermenu.o: src/game/scenes/charactermenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/detailspanel.o: src/game/scenes/detailspanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dialguemenu.o: src/game/scenes/dialguemenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/endscene.o: src/game/scenes/endscene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/enduilayer.o: src/game/scenes/enduilayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gamescene.o: src/game/scenes/gamescene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/gameuilayer.o: src/game/scenes/gameuilayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mapmenu.o: src/game/scenes/mapmenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/modulemenu.o: src/game/scenes/modulemenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pausemenu.o: src/game/scenes/pausemenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shelterscene.o: src/game/scenes/shelterscene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shelteruilayer.o: src/game/scenes/shelteruilayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spelldetailspanel.o: src/game/scenes/spelldetailspanel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spellgenmenu.o: src/game/scenes/spellgenmenu.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spellpreview.o: src/game/scenes/spellpreview.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spellstatinterface.o: src/game/scenes/spellstatinterface.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/splashscene.o: src/game/scenes/splashscene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stagingscene.o: src/game/scenes/stagingscene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/staginguilayer.o: src/game/scenes/staginguilayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subscene.o: src/game/scenes/subscene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tilelayer.o: src/game/scenes/tilelayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/titlescene.o: src/game/scenes/titlescene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/titleuilayer.o: src/game/scenes/titleuilayer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/transitions.o: src/game/scenes/transitions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spelldata.o: src/game/spelldata.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/aoespell.o: src/game/spells/aoespell.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/boltspell.o: src/game/spells/boltspell.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/instantspell.o: src/game/spells/instantspell.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/statusbar.o: src/game/statusbar.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tradegrid.o: src/game/tradegrid.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/viewport.o: src/game/viewport.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: src/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif