# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  spacegame_config = debug

else ifeq ($(config),release)
  spacegame_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := spacegame

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

spacegame:
ifneq (,$(spacegame_config))
	@echo "==== Building spacegame ($(spacegame_config)) ===="
	@${MAKE} --no-print-directory -C . -f spacegame.make config=$(spacegame_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f spacegame.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   spacegame"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"